# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created: Thu Oct 24 11:48:03 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName(_fromUtf8("frmMain"))
        frmMain.resize(697, 660)
        self.gridLayout = QtGui.QGridLayout(frmMain)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblStatus = QtGui.QLabel(frmMain)
        self.lblStatus.setFrameShape(QtGui.QFrame.Panel)
        self.lblStatus.setFrameShadow(QtGui.QFrame.Raised)
        self.lblStatus.setLineWidth(1)
        self.lblStatus.setText(_fromUtf8(""))
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.gridLayout.addWidget(self.lblStatus, 1, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(frmMain)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 677, 616))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabImage = QtGui.QWidget()
        self.tabImage.setObjectName(_fromUtf8("tabImage"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabImage)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblSource = QtGui.QLabel(self.tabImage)
        self.lblSource.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSource.setObjectName(_fromUtf8("lblSource"))
        self.gridLayout_2.addWidget(self.lblSource, 0, 0, 1, 1)
        self.imgVideo = QtGui.QGraphicsView(self.tabImage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgVideo.sizePolicy().hasHeightForWidth())
        self.imgVideo.setSizePolicy(sizePolicy)
        self.imgVideo.setResizeAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.imgVideo.setObjectName(_fromUtf8("imgVideo"))
        self.gridLayout_2.addWidget(self.imgVideo, 0, 2, 5, 4)
        self.txtSource = QtGui.QLineEdit(self.tabImage)
        self.txtSource.setObjectName(_fromUtf8("txtSource"))
        self.gridLayout_2.addWidget(self.txtSource, 1, 0, 1, 2)
        self.cmdAddSource = QtGui.QPushButton(self.tabImage)
        self.cmdAddSource.setObjectName(_fromUtf8("cmdAddSource"))
        self.gridLayout_2.addWidget(self.cmdAddSource, 2, 0, 1, 1)
        self.cmdSearchSources = QtGui.QPushButton(self.tabImage)
        self.cmdSearchSources.setObjectName(_fromUtf8("cmdSearchSources"))
        self.gridLayout_2.addWidget(self.cmdSearchSources, 2, 1, 1, 1)
        self.cmdAddFile = QtGui.QPushButton(self.tabImage)
        self.cmdAddFile.setObjectName(_fromUtf8("cmdAddFile"))
        self.gridLayout_2.addWidget(self.cmdAddFile, 3, 0, 1, 1)
        self.lblImgSize = QtGui.QLabel(self.tabImage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImgSize.sizePolicy().hasHeightForWidth())
        self.lblImgSize.setSizePolicy(sizePolicy)
        self.lblImgSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblImgSize.setObjectName(_fromUtf8("lblImgSize"))
        self.gridLayout_2.addWidget(self.lblImgSize, 5, 2, 1, 1)
        self.cmbImgSize = QtGui.QComboBox(self.tabImage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbImgSize.sizePolicy().hasHeightForWidth())
        self.cmbImgSize.setSizePolicy(sizePolicy)
        self.cmbImgSize.setMaxVisibleItems(5)
        self.cmbImgSize.setObjectName(_fromUtf8("cmbImgSize"))
        self.gridLayout_2.addWidget(self.cmbImgSize, 5, 3, 1, 1)
        self.cmdStartVideo = QtGui.QPushButton(self.tabImage)
        self.cmdStartVideo.setObjectName(_fromUtf8("cmdStartVideo"))
        self.gridLayout_2.addWidget(self.cmdStartVideo, 5, 4, 1, 1)
        self.cmdStopVideo = QtGui.QPushButton(self.tabImage)
        self.cmdStopVideo.setObjectName(_fromUtf8("cmdStopVideo"))
        self.gridLayout_2.addWidget(self.cmdStopVideo, 5, 5, 1, 1)
        self.lblConversion = QtGui.QLabel(self.tabImage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblConversion.sizePolicy().hasHeightForWidth())
        self.lblConversion.setSizePolicy(sizePolicy)
        self.lblConversion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblConversion.setObjectName(_fromUtf8("lblConversion"))
        self.gridLayout_2.addWidget(self.lblConversion, 6, 2, 1, 1)
        self.cmbConversion = QtGui.QComboBox(self.tabImage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConversion.sizePolicy().hasHeightForWidth())
        self.cmbConversion.setSizePolicy(sizePolicy)
        self.cmbConversion.setMaxVisibleItems(5)
        self.cmbConversion.setObjectName(_fromUtf8("cmbConversion"))
        self.gridLayout_2.addWidget(self.cmbConversion, 6, 3, 1, 1)
        self.cmdCoriander = QtGui.QPushButton(self.tabImage)
        self.cmdCoriander.setObjectName(_fromUtf8("cmdCoriander"))
        self.gridLayout_2.addWidget(self.cmdCoriander, 6, 4, 1, 2)
        self.lstSources = QtGui.QListWidget(self.tabImage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstSources.sizePolicy().hasHeightForWidth())
        self.lstSources.setSizePolicy(sizePolicy)
        self.lstSources.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lstSources.setObjectName(_fromUtf8("lstSources"))
        self.gridLayout_2.addWidget(self.lstSources, 4, 0, 1, 2)
        self.cmdDelSource = QtGui.QPushButton(self.tabImage)
        self.cmdDelSource.setObjectName(_fromUtf8("cmdDelSource"))
        self.gridLayout_2.addWidget(self.cmdDelSource, 5, 0, 1, 2)
        self.tabWidget.addTab(self.tabImage, _fromUtf8(""))
        self.tabDistortion = QtGui.QWidget()
        self.tabDistortion.setObjectName(_fromUtf8("tabDistortion"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabDistortion)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.grbUnfisheye = QtGui.QGroupBox(self.tabDistortion)
        self.grbUnfisheye.setAlignment(QtCore.Qt.AlignCenter)
        self.grbUnfisheye.setFlat(False)
        self.grbUnfisheye.setCheckable(False)
        self.grbUnfisheye.setObjectName(_fromUtf8("grbUnfisheye"))
        self.gridLayout_4 = QtGui.QGridLayout(self.grbUnfisheye)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget = QtGui.QWidget(self.grbUnfisheye)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(300, 500))
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.lblPatternX = QtGui.QLabel(self.widget)
        self.lblPatternX.setGeometry(QtCore.QRect(60, 22, 71, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPatternX.sizePolicy().hasHeightForWidth())
        self.lblPatternX.setSizePolicy(sizePolicy)
        self.lblPatternX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternX.setObjectName(_fromUtf8("lblPatternX"))
        self.lblPatternY = QtGui.QLabel(self.widget)
        self.lblPatternY.setGeometry(QtCore.QRect(178, 22, 71, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPatternY.sizePolicy().hasHeightForWidth())
        self.lblPatternY.setSizePolicy(sizePolicy)
        self.lblPatternY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternY.setObjectName(_fromUtf8("lblPatternY"))
        self.txtPatternX = QtGui.QLineEdit(self.widget)
        self.txtPatternX.setGeometry(QtCore.QRect(140, 22, 31, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPatternX.sizePolicy().hasHeightForWidth())
        self.txtPatternX.setSizePolicy(sizePolicy)
        self.txtPatternX.setObjectName(_fromUtf8("txtPatternX"))
        self.txtPatternY = QtGui.QLineEdit(self.widget)
        self.txtPatternY.setGeometry(QtCore.QRect(260, 22, 31, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPatternY.sizePolicy().hasHeightForWidth())
        self.txtPatternY.setSizePolicy(sizePolicy)
        self.txtPatternY.setObjectName(_fromUtf8("txtPatternY"))
        self.chkCropConvBefore = QtGui.QCheckBox(self.widget)
        self.chkCropConvBefore.setGeometry(QtCore.QRect(10, 290, 281, 22))
        self.chkCropConvBefore.setChecked(True)
        self.chkCropConvBefore.setObjectName(_fromUtf8("chkCropConvBefore"))
        self.txtCalibrationFrames = QtGui.QLineEdit(self.widget)
        self.txtCalibrationFrames.setGeometry(QtCore.QRect(260, 70, 31, 27))
        self.txtCalibrationFrames.setObjectName(_fromUtf8("txtCalibrationFrames"))
        self.txtCalibrationSquareSize = QtGui.QLineEdit(self.widget)
        self.txtCalibrationSquareSize.setGeometry(QtCore.QRect(260, 103, 31, 27))
        self.txtCalibrationSquareSize.setObjectName(_fromUtf8("txtCalibrationSquareSize"))
        self.lblCalibrationSquareSize = QtGui.QLabel(self.widget)
        self.lblCalibrationSquareSize.setGeometry(QtCore.QRect(180, 106, 72, 21))
        self.lblCalibrationSquareSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCalibrationSquareSize.setObjectName(_fromUtf8("lblCalibrationSquareSize"))
        self.lblCalibrationFrames = QtGui.QLabel(self.widget)
        self.lblCalibrationFrames.setGeometry(QtCore.QRect(80, 70, 174, 21))
        self.lblCalibrationFrames.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCalibrationFrames.setObjectName(_fromUtf8("lblCalibrationFrames"))
        self.chkCropImgManual = QtGui.QGroupBox(self.widget)
        self.chkCropImgManual.setGeometry(QtCore.QRect(10, 320, 281, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkCropImgManual.sizePolicy().hasHeightForWidth())
        self.chkCropImgManual.setSizePolicy(sizePolicy)
        self.chkCropImgManual.setCheckable(True)
        self.chkCropImgManual.setObjectName(_fromUtf8("chkCropImgManual"))
        self.txtBorderLR = QtGui.QLineEdit(self.chkCropImgManual)
        self.txtBorderLR.setGeometry(QtCore.QRect(250, 25, 31, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtBorderLR.sizePolicy().hasHeightForWidth())
        self.txtBorderLR.setSizePolicy(sizePolicy)
        self.txtBorderLR.setMinimumSize(QtCore.QSize(1, 0))
        self.txtBorderLR.setBaseSize(QtCore.QSize(0, 0))
        self.txtBorderLR.setObjectName(_fromUtf8("txtBorderLR"))
        self.txtBorderTB = QtGui.QLineEdit(self.chkCropImgManual)
        self.txtBorderTB.setGeometry(QtCore.QRect(250, 58, 31, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtBorderTB.sizePolicy().hasHeightForWidth())
        self.txtBorderTB.setSizePolicy(sizePolicy)
        self.txtBorderTB.setMinimumSize(QtCore.QSize(1, 0))
        self.txtBorderTB.setBaseSize(QtCore.QSize(0, 0))
        self.txtBorderTB.setObjectName(_fromUtf8("txtBorderTB"))
        self.lblImgBorderLR = QtGui.QLabel(self.chkCropImgManual)
        self.lblImgBorderLR.setGeometry(QtCore.QRect(80, 30, 161, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImgBorderLR.sizePolicy().hasHeightForWidth())
        self.lblImgBorderLR.setSizePolicy(sizePolicy)
        self.lblImgBorderLR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblImgBorderLR.setObjectName(_fromUtf8("lblImgBorderLR"))
        self.lblBorderTB = QtGui.QLabel(self.chkCropImgManual)
        self.lblBorderTB.setGeometry(QtCore.QRect(70, 60, 171, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBorderTB.sizePolicy().hasHeightForWidth())
        self.lblBorderTB.setSizePolicy(sizePolicy)
        self.lblBorderTB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblBorderTB.setObjectName(_fromUtf8("lblBorderTB"))
        self.chkCropImg = QtGui.QGroupBox(self.widget)
        self.chkCropImg.setEnabled(False)
        self.chkCropImg.setGeometry(QtCore.QRect(10, 420, 281, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkCropImg.sizePolicy().hasHeightForWidth())
        self.chkCropImg.setSizePolicy(sizePolicy)
        self.chkCropImg.setCheckable(True)
        self.chkCropImg.setChecked(False)
        self.chkCropImg.setObjectName(_fromUtf8("chkCropImg"))
        self.lblCalibrationBorders = QtGui.QLabel(self.chkCropImg)
        self.lblCalibrationBorders.setGeometry(QtCore.QRect(17, 29, 221, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCalibrationBorders.sizePolicy().hasHeightForWidth())
        self.lblCalibrationBorders.setSizePolicy(sizePolicy)
        self.lblCalibrationBorders.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCalibrationBorders.setObjectName(_fromUtf8("lblCalibrationBorders"))
        self.txtCalibrationBorders = QtGui.QLineEdit(self.chkCropImg)
        self.txtCalibrationBorders.setGeometry(QtCore.QRect(250, 20, 31, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCalibrationBorders.sizePolicy().hasHeightForWidth())
        self.txtCalibrationBorders.setSizePolicy(sizePolicy)
        self.txtCalibrationBorders.setObjectName(_fromUtf8("txtCalibrationBorders"))
        self.cmdCalibrateDistortion = QtGui.QPushButton(self.widget)
        self.cmdCalibrateDistortion.setGeometry(QtCore.QRect(120, 160, 87, 27))
        self.cmdCalibrateDistortion.setObjectName(_fromUtf8("cmdCalibrateDistortion"))
        self.cmdSaveDistortion = QtGui.QPushButton(self.widget)
        self.cmdSaveDistortion.setGeometry(QtCore.QRect(120, 190, 87, 27))
        self.cmdSaveDistortion.setObjectName(_fromUtf8("cmdSaveDistortion"))
        self.cmdLoadDistortion = QtGui.QPushButton(self.widget)
        self.cmdLoadDistortion.setGeometry(QtCore.QRect(120, 220, 87, 27))
        self.cmdLoadDistortion.setObjectName(_fromUtf8("cmdLoadDistortion"))
        self.gridLayout_4.addWidget(self.widget, 0, 2, 4, 1)
        self.grpFindChessPattern = QtGui.QGroupBox(self.grbUnfisheye)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpFindChessPattern.sizePolicy().hasHeightForWidth())
        self.grpFindChessPattern.setSizePolicy(sizePolicy)
        self.grpFindChessPattern.setMinimumSize(QtCore.QSize(280, 140))
        self.grpFindChessPattern.setObjectName(_fromUtf8("grpFindChessPattern"))
        self.txtPatternXMin = QtGui.QLineEdit(self.grpFindChessPattern)
        self.txtPatternXMin.setGeometry(QtCore.QRect(240, 30, 31, 27))
        self.txtPatternXMin.setObjectName(_fromUtf8("txtPatternXMin"))
        self.txtPatternYMax = QtGui.QLineEdit(self.grpFindChessPattern)
        self.txtPatternYMax.setGeometry(QtCore.QRect(111, 68, 31, 27))
        self.txtPatternYMax.setObjectName(_fromUtf8("txtPatternYMax"))
        self.txtPatternYMin = QtGui.QLineEdit(self.grpFindChessPattern)
        self.txtPatternYMin.setGeometry(QtCore.QRect(240, 68, 31, 27))
        self.txtPatternYMin.setObjectName(_fromUtf8("txtPatternYMin"))
        self.txtPatternXMax = QtGui.QLineEdit(self.grpFindChessPattern)
        self.txtPatternXMax.setGeometry(QtCore.QRect(111, 30, 31, 27))
        self.txtPatternXMax.setObjectName(_fromUtf8("txtPatternXMax"))
        self.lblPatternXMin = QtGui.QLabel(self.grpFindChessPattern)
        self.lblPatternXMin.setGeometry(QtCore.QRect(150, 30, 86, 21))
        self.lblPatternXMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternXMin.setObjectName(_fromUtf8("lblPatternXMin"))
        self.cmdFindPattern = QtGui.QPushButton(self.grpFindChessPattern)
        self.cmdFindPattern.setGeometry(QtCore.QRect(111, 106, 126, 27))
        self.cmdFindPattern.setObjectName(_fromUtf8("cmdFindPattern"))
        self.lblPatternYMin = QtGui.QLabel(self.grpFindChessPattern)
        self.lblPatternYMin.setGeometry(QtCore.QRect(150, 68, 85, 21))
        self.lblPatternYMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternYMin.setObjectName(_fromUtf8("lblPatternYMin"))
        self.lblPatternXMax = QtGui.QLabel(self.grpFindChessPattern)
        self.lblPatternXMax.setGeometry(QtCore.QRect(17, 30, 88, 21))
        self.lblPatternXMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternXMax.setObjectName(_fromUtf8("lblPatternXMax"))
        self.lblPatternYMax = QtGui.QLabel(self.grpFindChessPattern)
        self.lblPatternYMax.setGeometry(QtCore.QRect(17, 68, 88, 21))
        self.lblPatternYMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternYMax.setObjectName(_fromUtf8("lblPatternYMax"))
        self.gridLayout_4.addWidget(self.grpFindChessPattern, 3, 0, 1, 1)
        self.imgDistortion = QtGui.QGraphicsView(self.grbUnfisheye)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgDistortion.sizePolicy().hasHeightForWidth())
        self.imgDistortion.setSizePolicy(sizePolicy)
        self.imgDistortion.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imgDistortion.setObjectName(_fromUtf8("imgDistortion"))
        self.gridLayout_4.addWidget(self.imgDistortion, 0, 0, 3, 1)
        self.gridLayout_3.addWidget(self.grbUnfisheye, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabDistortion, _fromUtf8(""))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.grbTransformation = QtGui.QGroupBox(self.tabSettings)
        self.grbTransformation.setGeometry(QtCore.QRect(10, 0, 771, 541))
        self.grbTransformation.setAlignment(QtCore.Qt.AlignCenter)
        self.grbTransformation.setFlat(False)
        self.grbTransformation.setCheckable(False)
        self.grbTransformation.setObjectName(_fromUtf8("grbTransformation"))
        self.cmdCalibrateTransformation = QtGui.QPushButton(self.grbTransformation)
        self.cmdCalibrateTransformation.setGeometry(QtCore.QRect(600, 210, 87, 27))
        self.cmdCalibrateTransformation.setObjectName(_fromUtf8("cmdCalibrateTransformation"))
        self.imgTransformation = QtGui.QGraphicsView(self.grbTransformation)
        self.imgTransformation.setGeometry(QtCore.QRect(10, 20, 480, 360))
        self.imgTransformation.setObjectName(_fromUtf8("imgTransformation"))
        self.tabWidget.addTab(self.tabSettings, _fromUtf8(""))
        self.tabRecognition = QtGui.QWidget()
        self.tabRecognition.setObjectName(_fromUtf8("tabRecognition"))
        self.grbRecognition = QtGui.QGroupBox(self.tabRecognition)
        self.grbRecognition.setGeometry(QtCore.QRect(10, 0, 771, 541))
        self.grbRecognition.setAlignment(QtCore.Qt.AlignCenter)
        self.grbRecognition.setFlat(False)
        self.grbRecognition.setCheckable(False)
        self.grbRecognition.setObjectName(_fromUtf8("grbRecognition"))
        self.cmdStartRecognition = QtGui.QPushButton(self.grbRecognition)
        self.cmdStartRecognition.setGeometry(QtCore.QRect(600, 210, 87, 27))
        self.cmdStartRecognition.setObjectName(_fromUtf8("cmdStartRecognition"))
        self.imgRecognition = QtGui.QGraphicsView(self.grbRecognition)
        self.imgRecognition.setGeometry(QtCore.QRect(10, 20, 480, 360))
        self.imgRecognition.setObjectName(_fromUtf8("imgRecognition"))
        self.cmdStopRecognition = QtGui.QPushButton(self.grbRecognition)
        self.cmdStopRecognition.setGeometry(QtCore.QRect(600, 240, 87, 27))
        self.cmdStopRecognition.setObjectName(_fromUtf8("cmdStopRecognition"))
        self.tabWidget.addTab(self.tabRecognition, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(frmMain)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(_translate("frmMain", "mrVision", None))
        self.lblSource.setText(_translate("frmMain", "Source:", None))
        self.txtSource.setText(_translate("frmMain", "0", None))
        self.cmdAddSource.setText(_translate("frmMain", "&Add", None))
        self.cmdSearchSources.setText(_translate("frmMain", "&Search", None))
        self.cmdAddFile.setText(_translate("frmMain", "Add &File", None))
        self.lblImgSize.setText(_translate("frmMain", "Size:", None))
        self.cmdStartVideo.setText(_translate("frmMain", "&Start", None))
        self.cmdStopVideo.setText(_translate("frmMain", "S&top", None))
        self.lblConversion.setText(_translate("frmMain", "Conversion:", None))
        self.cmdCoriander.setText(_translate("frmMain", "Start Coriander", None))
        self.cmdDelSource.setText(_translate("frmMain", "&Remove", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImage), _translate("frmMain", "Video", None))
        self.grbUnfisheye.setTitle(_translate("frmMain", "Distortion", None))
        self.lblPatternX.setText(_translate("frmMain", "Corners X:", None))
        self.lblPatternY.setText(_translate("frmMain", "Corners Y:", None))
        self.txtPatternX.setText(_translate("frmMain", "5", None))
        self.txtPatternY.setText(_translate("frmMain", "8", None))
        self.chkCropConvBefore.setText(_translate("frmMain", "Convert from BGR to RGB before crop", None))
        self.txtCalibrationFrames.setText(_translate("frmMain", "3", None))
        self.txtCalibrationSquareSize.setText(_translate("frmMain", "1.0", None))
        self.lblCalibrationSquareSize.setText(_translate("frmMain", "Square size:", None))
        self.lblCalibrationFrames.setText(_translate("frmMain", "No. of frames for calibration:", None))
        self.chkCropImgManual.setTitle(_translate("frmMain", "Manual crop image", None))
        self.txtBorderLR.setText(_translate("frmMain", "10", None))
        self.txtBorderTB.setText(_translate("frmMain", "10", None))
        self.lblImgBorderLR.setText(_translate("frmMain", "Border left/right [px]:", None))
        self.lblBorderTB.setText(_translate("frmMain", "Border top/bottom [px]:", None))
        self.chkCropImg.setTitle(_translate("frmMain", "Auto crop image", None))
        self.lblCalibrationBorders.setText(_translate("frmMain", "Additional borders [%]", None))
        self.txtCalibrationBorders.setText(_translate("frmMain", "10", None))
        self.cmdCalibrateDistortion.setText(_translate("frmMain", "&Calibrate", None))
        self.cmdSaveDistortion.setText(_translate("frmMain", "&Save", None))
        self.cmdLoadDistortion.setText(_translate("frmMain", "&Load", None))
        self.grpFindChessPattern.setTitle(_translate("frmMain", "Search chess pattern", None))
        self.txtPatternXMin.setText(_translate("frmMain", "3", None))
        self.txtPatternYMax.setText(_translate("frmMain", "10", None))
        self.txtPatternYMin.setText(_translate("frmMain", "3", None))
        self.txtPatternXMax.setText(_translate("frmMain", "10", None))
        self.lblPatternXMin.setText(_translate("frmMain", "Pattern X min:", None))
        self.cmdFindPattern.setText(_translate("frmMain", "&Find chess pattern", None))
        self.lblPatternYMin.setText(_translate("frmMain", "Pattern Y min:", None))
        self.lblPatternXMax.setText(_translate("frmMain", "Pattern X max:", None))
        self.lblPatternYMax.setText(_translate("frmMain", "Pattern Y max:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDistortion), _translate("frmMain", "Distortion", None))
        self.grbTransformation.setTitle(_translate("frmMain", "Transformation", None))
        self.cmdCalibrateTransformation.setText(_translate("frmMain", "Calibra&te", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("frmMain", "Transformation", None))
        self.grbRecognition.setTitle(_translate("frmMain", "Object Recognition", None))
        self.cmdStartRecognition.setText(_translate("frmMain", "&Start", None))
        self.cmdStopRecognition.setText(_translate("frmMain", "S&top", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRecognition), _translate("frmMain", "Object Recognition", None))

