# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created: Wed Oct 23 17:13:24 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName(_fromUtf8("frmMain"))
        frmMain.resize(793, 622)
        self.tabWidget = QtGui.QTabWidget(frmMain)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 591))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabImage = QtGui.QWidget()
        self.tabImage.setObjectName(_fromUtf8("tabImage"))
        self.imgVideo = QtGui.QGraphicsView(self.tabImage)
        self.imgVideo.setGeometry(QtCore.QRect(199, 10, 581, 461))
        self.imgVideo.setResizeAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.imgVideo.setObjectName(_fromUtf8("imgVideo"))
        self.cmdCoriander = QtGui.QPushButton(self.tabImage)
        self.cmdCoriander.setGeometry(QtCore.QRect(610, 520, 111, 31))
        self.cmdCoriander.setObjectName(_fromUtf8("cmdCoriander"))
        self.cmdStopVideo = QtGui.QPushButton(self.tabImage)
        self.cmdStopVideo.setGeometry(QtCore.QRect(670, 480, 111, 31))
        self.cmdStopVideo.setObjectName(_fromUtf8("cmdStopVideo"))
        self.cmdStartVideo = QtGui.QPushButton(self.tabImage)
        self.cmdStartVideo.setGeometry(QtCore.QRect(550, 480, 111, 31))
        self.cmdStartVideo.setObjectName(_fromUtf8("cmdStartVideo"))
        self.txtSource = QtGui.QLineEdit(self.tabImage)
        self.txtSource.setGeometry(QtCore.QRect(10, 40, 181, 27))
        self.txtSource.setObjectName(_fromUtf8("txtSource"))
        self.lblSource = QtGui.QLabel(self.tabImage)
        self.lblSource.setGeometry(QtCore.QRect(10, 10, 51, 31))
        self.lblSource.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSource.setObjectName(_fromUtf8("lblSource"))
        self.cmdAddSource = QtGui.QPushButton(self.tabImage)
        self.cmdAddSource.setGeometry(QtCore.QRect(10, 70, 87, 27))
        self.cmdAddSource.setObjectName(_fromUtf8("cmdAddSource"))
        self.cmbConversion = QtGui.QComboBox(self.tabImage)
        self.cmbConversion.setGeometry(QtCore.QRect(370, 520, 171, 27))
        self.cmbConversion.setMaxVisibleItems(5)
        self.cmbConversion.setObjectName(_fromUtf8("cmbConversion"))
        self.lblConversion = QtGui.QLabel(self.tabImage)
        self.lblConversion.setGeometry(QtCore.QRect(280, 520, 81, 31))
        self.lblConversion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblConversion.setObjectName(_fromUtf8("lblConversion"))
        self.cmdDelSource = QtGui.QPushButton(self.tabImage)
        self.cmdDelSource.setGeometry(QtCore.QRect(30, 520, 87, 27))
        self.cmdDelSource.setObjectName(_fromUtf8("cmdDelSource"))
        self.cmdAddFile = QtGui.QPushButton(self.tabImage)
        self.cmdAddFile.setGeometry(QtCore.QRect(10, 110, 87, 27))
        self.cmdAddFile.setObjectName(_fromUtf8("cmdAddFile"))
        self.cmdSearchSources = QtGui.QPushButton(self.tabImage)
        self.cmdSearchSources.setGeometry(QtCore.QRect(100, 70, 87, 27))
        self.cmdSearchSources.setObjectName(_fromUtf8("cmdSearchSources"))
        self.lstSources = QtGui.QListWidget(self.tabImage)
        self.lstSources.setGeometry(QtCore.QRect(10, 180, 181, 331))
        self.lstSources.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lstSources.setObjectName(_fromUtf8("lstSources"))
        self.cmbImgSize = QtGui.QComboBox(self.tabImage)
        self.cmbImgSize.setGeometry(QtCore.QRect(370, 480, 171, 27))
        self.cmbImgSize.setMaxVisibleItems(5)
        self.cmbImgSize.setObjectName(_fromUtf8("cmbImgSize"))
        self.lblImgSize = QtGui.QLabel(self.tabImage)
        self.lblImgSize.setGeometry(QtCore.QRect(280, 480, 81, 31))
        self.lblImgSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblImgSize.setObjectName(_fromUtf8("lblImgSize"))
        self.tabWidget.addTab(self.tabImage, _fromUtf8(""))
        self.tabDistortion = QtGui.QWidget()
        self.tabDistortion.setObjectName(_fromUtf8("tabDistortion"))
        self.grbUnfisheye = QtGui.QGroupBox(self.tabDistortion)
        self.grbUnfisheye.setGeometry(QtCore.QRect(10, 0, 771, 551))
        self.grbUnfisheye.setAlignment(QtCore.Qt.AlignCenter)
        self.grbUnfisheye.setFlat(False)
        self.grbUnfisheye.setCheckable(False)
        self.grbUnfisheye.setObjectName(_fromUtf8("grbUnfisheye"))
        self.cmdCalibrateDistortion = QtGui.QPushButton(self.grbUnfisheye)
        self.cmdCalibrateDistortion.setGeometry(QtCore.QRect(590, 150, 87, 27))
        self.cmdCalibrateDistortion.setObjectName(_fromUtf8("cmdCalibrateDistortion"))
        self.imgDistortion = QtGui.QGraphicsView(self.grbUnfisheye)
        self.imgDistortion.setGeometry(QtCore.QRect(0, 30, 480, 360))
        self.imgDistortion.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imgDistortion.setObjectName(_fromUtf8("imgDistortion"))
        self.lblPatternY = QtGui.QLabel(self.grbUnfisheye)
        self.lblPatternY.setGeometry(QtCore.QRect(630, 30, 91, 21))
        self.lblPatternY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternY.setObjectName(_fromUtf8("lblPatternY"))
        self.txtPatternY = QtGui.QLineEdit(self.grbUnfisheye)
        self.txtPatternY.setGeometry(QtCore.QRect(730, 30, 41, 27))
        self.txtPatternY.setObjectName(_fromUtf8("txtPatternY"))
        self.txtPatternX = QtGui.QLineEdit(self.grbUnfisheye)
        self.txtPatternX.setGeometry(QtCore.QRect(560, 30, 41, 27))
        self.txtPatternX.setObjectName(_fromUtf8("txtPatternX"))
        self.lblPatternX = QtGui.QLabel(self.grbUnfisheye)
        self.lblPatternX.setGeometry(QtCore.QRect(490, 30, 61, 21))
        self.lblPatternX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternX.setObjectName(_fromUtf8("lblPatternX"))
        self.txtCalibrationFrames = QtGui.QLineEdit(self.grbUnfisheye)
        self.txtCalibrationFrames.setGeometry(QtCore.QRect(730, 70, 41, 27))
        self.txtCalibrationFrames.setObjectName(_fromUtf8("txtCalibrationFrames"))
        self.lblCalibrationFrames = QtGui.QLabel(self.grbUnfisheye)
        self.lblCalibrationFrames.setGeometry(QtCore.QRect(490, 70, 231, 21))
        self.lblCalibrationFrames.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCalibrationFrames.setObjectName(_fromUtf8("lblCalibrationFrames"))
        self.lblCalibrationSquareSize = QtGui.QLabel(self.grbUnfisheye)
        self.lblCalibrationSquareSize.setGeometry(QtCore.QRect(490, 100, 231, 21))
        self.lblCalibrationSquareSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCalibrationSquareSize.setObjectName(_fromUtf8("lblCalibrationSquareSize"))
        self.txtCalibrationSquareSize = QtGui.QLineEdit(self.grbUnfisheye)
        self.txtCalibrationSquareSize.setGeometry(QtCore.QRect(730, 100, 41, 27))
        self.txtCalibrationSquareSize.setObjectName(_fromUtf8("txtCalibrationSquareSize"))
        self.grpFindChessPattern = QtGui.QGroupBox(self.grbUnfisheye)
        self.grpFindChessPattern.setGeometry(QtCore.QRect(10, 410, 321, 131))
        self.grpFindChessPattern.setObjectName(_fromUtf8("grpFindChessPattern"))
        self.txtPatternXMin = QtGui.QLineEdit(self.grpFindChessPattern)
        self.txtPatternXMin.setGeometry(QtCore.QRect(270, 30, 41, 27))
        self.txtPatternXMin.setObjectName(_fromUtf8("txtPatternXMin"))
        self.txtPatternYMax = QtGui.QLineEdit(self.grpFindChessPattern)
        self.txtPatternYMax.setGeometry(QtCore.QRect(100, 60, 41, 27))
        self.txtPatternYMax.setObjectName(_fromUtf8("txtPatternYMax"))
        self.txtPatternYMin = QtGui.QLineEdit(self.grpFindChessPattern)
        self.txtPatternYMin.setGeometry(QtCore.QRect(270, 60, 41, 27))
        self.txtPatternYMin.setObjectName(_fromUtf8("txtPatternYMin"))
        self.txtPatternXMax = QtGui.QLineEdit(self.grpFindChessPattern)
        self.txtPatternXMax.setGeometry(QtCore.QRect(100, 30, 41, 27))
        self.txtPatternXMax.setObjectName(_fromUtf8("txtPatternXMax"))
        self.lblPatternXMin = QtGui.QLabel(self.grpFindChessPattern)
        self.lblPatternXMin.setGeometry(QtCore.QRect(170, 30, 91, 21))
        self.lblPatternXMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternXMin.setObjectName(_fromUtf8("lblPatternXMin"))
        self.cmdFindPattern = QtGui.QPushButton(self.grpFindChessPattern)
        self.cmdFindPattern.setGeometry(QtCore.QRect(100, 100, 131, 27))
        self.cmdFindPattern.setObjectName(_fromUtf8("cmdFindPattern"))
        self.lblPatternYMin = QtGui.QLabel(self.grpFindChessPattern)
        self.lblPatternYMin.setGeometry(QtCore.QRect(170, 60, 91, 21))
        self.lblPatternYMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternYMin.setObjectName(_fromUtf8("lblPatternYMin"))
        self.lblPatternXMax = QtGui.QLabel(self.grpFindChessPattern)
        self.lblPatternXMax.setGeometry(QtCore.QRect(0, 30, 91, 21))
        self.lblPatternXMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternXMax.setObjectName(_fromUtf8("lblPatternXMax"))
        self.lblPatternYMax = QtGui.QLabel(self.grpFindChessPattern)
        self.lblPatternYMax.setGeometry(QtCore.QRect(0, 60, 91, 21))
        self.lblPatternYMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPatternYMax.setObjectName(_fromUtf8("lblPatternYMax"))
        self.chkCropImg = QtGui.QGroupBox(self.grbUnfisheye)
        self.chkCropImg.setEnabled(False)
        self.chkCropImg.setGeometry(QtCore.QRect(490, 400, 281, 91))
        self.chkCropImg.setCheckable(True)
        self.chkCropImg.setChecked(False)
        self.chkCropImg.setObjectName(_fromUtf8("chkCropImg"))
        self.lblCalibrationBorders = QtGui.QLabel(self.chkCropImg)
        self.lblCalibrationBorders.setGeometry(QtCore.QRect(10, 40, 211, 21))
        self.lblCalibrationBorders.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCalibrationBorders.setObjectName(_fromUtf8("lblCalibrationBorders"))
        self.txtCalibrationBorders = QtGui.QLineEdit(self.chkCropImg)
        self.txtCalibrationBorders.setGeometry(QtCore.QRect(230, 40, 41, 27))
        self.txtCalibrationBorders.setObjectName(_fromUtf8("txtCalibrationBorders"))
        self.cmdLoadDistortion = QtGui.QPushButton(self.grbUnfisheye)
        self.cmdLoadDistortion.setGeometry(QtCore.QRect(590, 230, 87, 27))
        self.cmdLoadDistortion.setObjectName(_fromUtf8("cmdLoadDistortion"))
        self.cmdSaveDistortion = QtGui.QPushButton(self.grbUnfisheye)
        self.cmdSaveDistortion.setGeometry(QtCore.QRect(590, 200, 87, 27))
        self.cmdSaveDistortion.setObjectName(_fromUtf8("cmdSaveDistortion"))
        self.chkCropImgManual = QtGui.QGroupBox(self.grbUnfisheye)
        self.chkCropImgManual.setGeometry(QtCore.QRect(490, 290, 281, 91))
        self.chkCropImgManual.setCheckable(True)
        self.chkCropImgManual.setObjectName(_fromUtf8("chkCropImgManual"))
        self.txtBorderLR = QtGui.QLineEdit(self.chkCropImgManual)
        self.txtBorderLR.setGeometry(QtCore.QRect(220, 30, 51, 27))
        self.txtBorderLR.setObjectName(_fromUtf8("txtBorderLR"))
        self.txtBorderTB = QtGui.QLineEdit(self.chkCropImgManual)
        self.txtBorderTB.setGeometry(QtCore.QRect(220, 60, 51, 27))
        self.txtBorderTB.setObjectName(_fromUtf8("txtBorderTB"))
        self.lblImgBorderLR = QtGui.QLabel(self.chkCropImgManual)
        self.lblImgBorderLR.setGeometry(QtCore.QRect(20, 30, 191, 21))
        self.lblImgBorderLR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblImgBorderLR.setObjectName(_fromUtf8("lblImgBorderLR"))
        self.lblBorderTB = QtGui.QLabel(self.chkCropImgManual)
        self.lblBorderTB.setGeometry(QtCore.QRect(20, 60, 191, 21))
        self.lblBorderTB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblBorderTB.setObjectName(_fromUtf8("lblBorderTB"))
        self.chkCropConvBefore = QtGui.QCheckBox(self.grbUnfisheye)
        self.chkCropConvBefore.setGeometry(QtCore.QRect(490, 480, 281, 22))
        self.chkCropConvBefore.setChecked(True)
        self.chkCropConvBefore.setObjectName(_fromUtf8("chkCropConvBefore"))
        self.tabWidget.addTab(self.tabDistortion, _fromUtf8(""))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.grbTransformation = QtGui.QGroupBox(self.tabSettings)
        self.grbTransformation.setGeometry(QtCore.QRect(10, 0, 771, 541))
        self.grbTransformation.setAlignment(QtCore.Qt.AlignCenter)
        self.grbTransformation.setFlat(False)
        self.grbTransformation.setCheckable(False)
        self.grbTransformation.setObjectName(_fromUtf8("grbTransformation"))
        self.cmdCalibrateTransformation = QtGui.QPushButton(self.grbTransformation)
        self.cmdCalibrateTransformation.setGeometry(QtCore.QRect(600, 210, 87, 27))
        self.cmdCalibrateTransformation.setObjectName(_fromUtf8("cmdCalibrateTransformation"))
        self.imgTransformation = QtGui.QGraphicsView(self.grbTransformation)
        self.imgTransformation.setGeometry(QtCore.QRect(10, 20, 480, 360))
        self.imgTransformation.setObjectName(_fromUtf8("imgTransformation"))
        self.tabWidget.addTab(self.tabSettings, _fromUtf8(""))
        self.tabRecognition = QtGui.QWidget()
        self.tabRecognition.setObjectName(_fromUtf8("tabRecognition"))
        self.grbRecognition = QtGui.QGroupBox(self.tabRecognition)
        self.grbRecognition.setGeometry(QtCore.QRect(10, 0, 771, 541))
        self.grbRecognition.setAlignment(QtCore.Qt.AlignCenter)
        self.grbRecognition.setFlat(False)
        self.grbRecognition.setCheckable(False)
        self.grbRecognition.setObjectName(_fromUtf8("grbRecognition"))
        self.cmdStartRecognition = QtGui.QPushButton(self.grbRecognition)
        self.cmdStartRecognition.setGeometry(QtCore.QRect(600, 210, 87, 27))
        self.cmdStartRecognition.setObjectName(_fromUtf8("cmdStartRecognition"))
        self.imgRecognition = QtGui.QGraphicsView(self.grbRecognition)
        self.imgRecognition.setGeometry(QtCore.QRect(10, 20, 480, 360))
        self.imgRecognition.setObjectName(_fromUtf8("imgRecognition"))
        self.cmdStopRecognition = QtGui.QPushButton(self.grbRecognition)
        self.cmdStopRecognition.setGeometry(QtCore.QRect(600, 240, 87, 27))
        self.cmdStopRecognition.setObjectName(_fromUtf8("cmdStopRecognition"))
        self.tabWidget.addTab(self.tabRecognition, _fromUtf8(""))
        self.lblStatus = QtGui.QLabel(frmMain)
        self.lblStatus.setGeometry(QtCore.QRect(0, 596, 791, 21))
        self.lblStatus.setFrameShape(QtGui.QFrame.Panel)
        self.lblStatus.setFrameShadow(QtGui.QFrame.Raised)
        self.lblStatus.setLineWidth(1)
        self.lblStatus.setText(_fromUtf8(""))
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))

        self.retranslateUi(frmMain)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(_translate("frmMain", "mrVision", None))
        self.cmdCoriander.setText(_translate("frmMain", "Start Coriander", None))
        self.cmdStopVideo.setText(_translate("frmMain", "S&top", None))
        self.cmdStartVideo.setText(_translate("frmMain", "&Start", None))
        self.txtSource.setText(_translate("frmMain", "0", None))
        self.lblSource.setText(_translate("frmMain", "Source:", None))
        self.cmdAddSource.setText(_translate("frmMain", "&Add", None))
        self.lblConversion.setText(_translate("frmMain", "Conversion:", None))
        self.cmdDelSource.setText(_translate("frmMain", "&Remove", None))
        self.cmdAddFile.setText(_translate("frmMain", "Add &File", None))
        self.cmdSearchSources.setText(_translate("frmMain", "&Search", None))
        self.lblImgSize.setText(_translate("frmMain", "Size:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImage), _translate("frmMain", "Video", None))
        self.grbUnfisheye.setTitle(_translate("frmMain", "Distortion", None))
        self.cmdCalibrateDistortion.setText(_translate("frmMain", "&Calibrate", None))
        self.lblPatternY.setText(_translate("frmMain", "Pattern Y:", None))
        self.txtPatternY.setText(_translate("frmMain", "8", None))
        self.txtPatternX.setText(_translate("frmMain", "5", None))
        self.lblPatternX.setText(_translate("frmMain", "Pattern X:", None))
        self.txtCalibrationFrames.setText(_translate("frmMain", "3", None))
        self.lblCalibrationFrames.setText(_translate("frmMain", "No. of frames for calibration:", None))
        self.lblCalibrationSquareSize.setText(_translate("frmMain", "Square size:", None))
        self.txtCalibrationSquareSize.setText(_translate("frmMain", "1.0", None))
        self.grpFindChessPattern.setTitle(_translate("frmMain", "Search chess pattern", None))
        self.txtPatternXMin.setText(_translate("frmMain", "3", None))
        self.txtPatternYMax.setText(_translate("frmMain", "10", None))
        self.txtPatternYMin.setText(_translate("frmMain", "3", None))
        self.txtPatternXMax.setText(_translate("frmMain", "10", None))
        self.lblPatternXMin.setText(_translate("frmMain", "Pattern X min:", None))
        self.cmdFindPattern.setText(_translate("frmMain", "&Find chess pattern", None))
        self.lblPatternYMin.setText(_translate("frmMain", "Pattern Y min:", None))
        self.lblPatternXMax.setText(_translate("frmMain", "Pattern X max:", None))
        self.lblPatternYMax.setText(_translate("frmMain", "Pattern Y max:", None))
        self.chkCropImg.setTitle(_translate("frmMain", "Auto crop image", None))
        self.lblCalibrationBorders.setText(_translate("frmMain", "Additional borders [%]", None))
        self.txtCalibrationBorders.setText(_translate("frmMain", "10", None))
        self.cmdLoadDistortion.setText(_translate("frmMain", "&Load", None))
        self.cmdSaveDistortion.setText(_translate("frmMain", "&Save", None))
        self.chkCropImgManual.setTitle(_translate("frmMain", "Manual crop image", None))
        self.txtBorderLR.setText(_translate("frmMain", "10", None))
        self.txtBorderTB.setText(_translate("frmMain", "10", None))
        self.lblImgBorderLR.setText(_translate("frmMain", "Border left/right [px]:", None))
        self.lblBorderTB.setText(_translate("frmMain", "Border top/bottom [px]:", None))
        self.chkCropConvBefore.setText(_translate("frmMain", "Convert from BGR to RGB before crop", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDistortion), _translate("frmMain", "Distortion", None))
        self.grbTransformation.setTitle(_translate("frmMain", "Transformation", None))
        self.cmdCalibrateTransformation.setText(_translate("frmMain", "Calibra&te", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("frmMain", "Transformation", None))
        self.grbRecognition.setTitle(_translate("frmMain", "Object Recognition", None))
        self.cmdStartRecognition.setText(_translate("frmMain", "&Start", None))
        self.cmdStopRecognition.setText(_translate("frmMain", "S&top", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRecognition), _translate("frmMain", "Object Recognition", None))

